[project]
name = "apache-beam-utils"
version = "0.1.3"
description = "A carefully extracted subset of utility modules from the Apache Beam Python SDK"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
